### ISSUE TITLE
Multiple Trees Open

### ISSUE THREAD

**Issue by TurtleP** [NicolaiSoeborg/filemanager-plugin#1]
Hi,

I've recently started messing with Micro and wanted to try out the plugin. It's amazing, but has a bug where if you press the command to 'open' it again, it creates *another* tree.

Thought I'd point this out.

Also, with this issue in mind, could it be possible to add a ``toggle`` command for the tree, rather than pressing escape?

Keep up the amazing work!

**Comment by NicolaiSoeborg** [comment]
I've released a new version with a `filemanager.ToggleTree`-command (note the new name `filetree` -> `filemanager`)
