### ISSUE TITLE
Need new release doing so plugin install works with latest bug fixes 

### ISSUE THREAD

**Issue by tommyshem** [NicolaiSoeborg/filemanager-plugin#18]
@NicolaiSoeborg  
Needs tag v2.1.1 or what ever number you think best.
Then release with bug fix info doing.
Then repo file needs updating so latest bug fixes can be pulled in with plug install in micro editor.
This release should have better windows support.

**Comment by NicolaiSoeborg** [comment]
Sorry for the  delay!

Version 2.1.1 has just been released now.
