### ISSUE TITLE
Plugin crashes on Android/Termux

### ISSUE THREAD

**Issue by sarimak** [NicolaiSoeborg/filemanager-plugin#2]
When the plugin is activated via Ctrl+E tree the plugin crashes when trying to list files in current directory:

```
<string>138: attempt to index a non-table object(nil)
stack traceback:
    <string>:138: in function 'scanDir'
    <string>:45: in function 'refreshTree'
    <string>:24: in function 'OpenTree'
    <string>:37: in main chunk
    [G]: ?
```

After pressing a key the left panel is empty.
Current directory as shown by **pwd** in Termux's commandline: **/data/data/com.termux/files/home**
The plugin is installed into: **/data/data/com.termux/files/home/.config/micro/plugins/filemanager**

**Comment by sarimak** [comment]
Listing the folder works:
```
t = {}
cwd = "/data/data/com.termux/files/home"
proc = io.popen('ls -Ap "'..cwd..'"')

for filename in proc:lines() do
    print(filename)
end
proc:close()
```
**lua test.lua** shows contents of current folder.

**Comment by NicolaiSoeborg** [comment]
Is the issue persistent or happens at random?

Can you test if this works (directly copy from the code):
```lua
isWin = false
driveLetter = "C:\\"
cwd = "/data/data/com.termux/files/home"

function scanDir(directory)
    local i, t, proc = 3, {}, nil
    t[1] = (isWin and driveLetter or "") .. cwd
    t[2] = ".."
    if isWin then
        proc = io.popen('dir /a /b "'..directory..'"')
    else
        proc = io.popen('ls -Ap "'..directory..'"')
    end
    for filename in proc:lines() do
        t[i] = filename
        i = i + 1
    end
    proc:close()
    return t
end

print(table.concat(scanDir(cwd), "\n "))
```

**Comment by sarimak** [comment]
The issue is persistent.
If I put the code you've provided into test2.lua in /data/data/com.termux/files/home and run lua test2.lua, it works and displays the contents of current directory.

**Comment by tommyshem** [comment]
Plugin has been  updated and should now work with Micro Editor version 1.3.2 and above.
Please leave feed back if it still does not work.

**Comment by tommyshem** [comment]
I have tested and it still does not work on android termux problem with io.popen on android. Looking into go standard library bindings to solve this problem hopefuly.

**Comment by sarimak** [comment]
I have compiled the latest micro from master and installed the plugin according to README and the plugin now works even on Android/Termux - many thanks for the fix!
