### ISSUE TITLE
filemanager does not work as expected

### ISSUE THREAD

**Issue by BogBel** [NicolaiSoeborg/filemanager-plugin#20]
I start micro in some dir 
~/project/temple
then inside micro in navigating via buildin cd command to another dir and start editing file there
But when in open filemanager it is still displays file tree which was on micro start.
Am i doing something wrong?
Is there is any workaround about this?

**Comment by sum01** [comment]
The working directory is only pulled on first load (when you open Micro), and it only changes if you directly go into a dir with filemanager. So if you `cd` to somewhere else, it won't "follow you".

A fix could be to do `cwd = WorkingDirectory()` inside of `openTree()`, but a callback to the `cd` command would need to be added to do the same.
