### ISSUE TITLE
[Feature Request] Add option to hide specific file patterns

### ISSUE THREAD

**Issue by AtomicCoding** [NicolaiSoeborg/filemanager-plugin#22]
A lot of files (i.e .DS_Store) just don't need to be displayed in the sidebar. A feature to hide specific file patterns would be really helpful.

**Comment by sum01** [comment]
So I've already looked into this a little bit, and while it's straight-forward to just check if the file starts with `.` on Unix, Windows requires syscalls. But I can try to get it working. Probably with an option like `filemanager-showhidden` that's default to `true`.

**Comment by sum01** [comment]
Or do you mean a sort of `.gitignore`-esque file just filemanager?

**Comment by AtomicCoding** [comment]
Both

**Comment by sum01** [comment]
Well I already added the option to hide dotfiles in my branch, but I could use the actual `.gitignore` (if it exists) as well.

I'm kind of hesitant to make a special "ignore" file, but I did want to integrate with git more, so having the option to hide git ignored files would be on track with that.

**Comment by sum01** [comment]
So for all intents and purposes, the code is finished to allow for hiding of gitignored files. The only issue at the moment is that there's a weird bug with string comparison always returning `false`, even when they match.
