### ISSUE TITLE
Crashes with: attempt to call a non-function object

### ISSUE THREAD

**Issue by oskarbraten** [NicolaiSoeborg/filemanager-plugin#28]
When selecting (by clicking or using tab) any file in the filetree the plugin crashes with the following message:

```
filemanager:548: attempt to call a non-function object
stack traceback:
	filemanager:548: in function 'try_open_at_y'
	filemanager:1124: in main chunk
	[G]: ?
```

Running in Terminal on elementaryOS.

**Comment by sum01** [comment]
Plugin and Micro version?

**Comment by oskarbraten** [comment]
Micro version: 1.4.0
Plugin version: 3.1.1

**Comment by sum01** [comment]
Oh, I know what it is. I switched to using `NewBufferFromFile` as per Zyedidia's recommendation, which he said was in Micro v1.4.0. I just checked and it's actually not in the "latest" release, but only in nightly.

I'll have to bump the minimum version to 1.4.1.

As for you, either upgrade to nightly, or downgrade the plugin.

**Comment by avently** [comment]
@sum01 after i installed v 3.1.0 i can't use your plugin. Seems like it doesn't respond to "Enter" key. So i can't open any file or go up to a folder but i can use left/right arrow keys to open a contents of a folders. I'm using micro v 1.4.1. Also for some reason micro didn't find new version of the plugin and i downloaded it manually. Now i have v 3.1.2 with the same problems. What can i do?

**Comment by sum01** [comment]
@avently The `tab` button (or mouseleft) is used for opening files/dirs. Everything is documented in the [README](https://github.com/NicolaiSoeborg/filemanager-plugin/blob/master/README.md)

And the failure to update thing seems to be a bug with Micro. You can read about it here https://github.com/zyedidia/micro/issues/906

**Comment by avently** [comment]
@sum01 its a little bit uncommon to use tab key for openning a file but ok, I will rebind the key. Thanks

**Comment by sum01** [comment]
@avently I had no choice but to change it to something else, since read-only mode disables the enter key entirely. The callback's for it just stop working, so I went with what felt natural.

Feel free to rebind it though. I created those API's listed in the README for users to change whatever they want.
