### ISSUE TITLE
Hide directory with left arrow from any position

### ISSUE THREAD

**Issue by avently** [NicolaiSoeborg/filemanager-plugin#29]
For example I'm opening a directory for viewing with right arrow key. Then i'm pressing down arrow multiple times and now i can't hide a directory with left arrow key. For this i should go up to "- directory name" and then I should press left arrow key. Can this be simpler? To handle left arrow key from any position in a directory

**Comment by sum01** [comment]
Not exactly the same, but you can already "goto-parent-dir" with Shift-Up, then hide it with the left arrow.

**Comment by avently** [comment]
yes, using it now until this issue will be resolved (or will use it forever). Shift-Up for some reason doesn't go to ".." (two dots) but for me it is logical if there is no visible parent directory.

**Comment by sum01** [comment]
Ah, I never bothered to write it to go to the `..` since you can always Ctrl-Up. I guess that could be added.

**Comment by avently** [comment]
Made all changes i asked in #30
