### ISSUE TITLE
Full path in folders and files

### ISSUE THREAD

**Issue by cofins** [NicolaiSoeborg/filemanager-plugin#36]
When I navigate in the folders, they have the name of the entire path where they are stored, and my question is if you can hide this route and only show the name of the folder.

![captura](https://user-images.githubusercontent.com/42383353/45459227-f9737380-b6bc-11e8-94e2-050f381e8a83.PNG)

**Comment by sum01** [comment]
They shouldn't show the full path. It's already programmed to get only the basename when it displays. Something must be wrong with the call to Golang's basename on Windows.

What version of the plugin, and what version of Windows do you have?

**Comment by cofins** [comment]
currently I have
- windows: 10 version 1803
- filemanager-plugin : 3.2.0

**Comment by sum01** [comment]
So according to [this](https://grokbase.com/t/gg/golang-nuts/166evsebss/go-nuts-how-to-properly-get-basename-under-dos) the Golang lib "path" Base function only works on Unix, while its "filepath" Base function works for Unix/Windows? 

It should be an easy enough fix, I think as simple as changing [this line](https://github.com/NicolaiSoeborg/filemanager-plugin/blob/57df3ff47841916587986beaecace2295970a0f0/filemanager.lua#L125) from `"path"` to `"filepath"` or maybe `"path/filepath"`, depending on what Micro requires.

**Comment by cofins** [comment]
Perfect, replacing it works by `"filepath"`.
Thank you very much for the information.
