### ISSUE TITLE
No documentation on how to show and hide the filemanager

### ISSUE THREAD

**Issue by jaqmol** [NicolaiSoeborg/filemanager-plugin#42]
Apparently I'm a bit blind at the moment, but I seem to be unable to find any documentation on how to actually show the filemanager after installing it.

**Comment by Lomomn** [comment]
The commands are on the readme/homescreen for this repo.
https://github.com/NicolaiSoeborg/filemanager-plugin#commands-and-keybindings

You can run a command with CtrlE, so hit that then type "tree" and press enter. :)
