### ISSUE TITLE
cwd doesn't seem to be working

### ISSUE THREAD

**Issue by oliver-daniel** [NicolaiSoeborg/filemanager-plugin#44]
Platform: OS X Mojave
Micro and this plugin are both at the latest build as of Aug 12, 2019.

No matter what directory I open Micro in, whenever I activate `tree`, it always starts me off in `~`. Looking through the source code, it seems as though it _should_ be opening in the active directory, but that doesn't appear to be happening.

What should I do?

Thanks!

**Comment by sum01** [comment]
So this plugin uses `WorkingDirectory()` to get the path, which Micro internally returns the result of https://golang.org/pkg/os/#Getwd ([see here](https://github.com/zyedidia/micro/blob/master/cmd/micro/micro.go#L438))

If that Golang call isn't working as expected, I would look at your terminal environment, or maybe check the issues on Micro's github page.

I don't really have any due process to fixing it via the plugin, unless there's a newer function call it should be using? Not sure, as I haven't kept up with Micro's development.

**Comment by sum01** [comment]
@oliver-daniel Are you still having this issue with everything up-to-date?

**Comment by sum01** [comment]
Closing this since it's been a while with no response, and I'm assuming it's no longer happening.
