### ISSUE TITLE
Changing drives under WIN

### ISSUE THREAD

**Issue by kpeters58** [NicolaiSoeborg/filemanager-plugin#45]
Is it a valid assessment that (for now?) one has to close the tree, issue a 'cd' to the new drive at micro level and then reopen the tree?

**Comment by sum01** [comment]
It should change when you use `cd`. See here https://github.com/NicolaiSoeborg/filemanager-plugin/blob/9f425078cdc789dff895e0a32d6a0d62a1e0bb77/filemanager.lua#L1196-L1210

**Comment by sum01** [comment]
I'm closing this since it seems this should already be a non-issue.

If you're still having an issue, please give me more info so we can try and figure it out.
