### ISSUE TITLE
Compress/uncompress a directory sounds misleading

### ISSUE THREAD

**Issue by muesli** [NicolaiSoeborg/filemanager-plugin#46]
Reading the README I was a bit confused by the term "to (un)compress directory". I assumed it's referring to extracting tar-archives or something. When I finally tried the cursor left/right keys to see what really happens, I realized it's expanding & collapsing directory listings.

Maybe `expand` and `collapse` are better - or at least less misleading - terms?

**Comment by sum01** [comment]
Sure, changing the wording to "expand" and "collapse" is fine.
