### ISSUE TITLE
How to use options?

### ISSUE THREAD

**Issue by andrewhavens** [NicolaiSoeborg/filemanager-plugin#49]
Sorry, I'm new to using Micro. It's not clear to me from the README how to use/specify the options. I'd like to set the `filemanager-openonstart` option to true. I assumed this was a setting, but I tried CtrlE + `set filemanager-openonstart true` and got the error "Invalid option". What am I doing wrong?

**Comment by andrewhavens** [comment]
Ah, I figured it out. It was actually `set filemanager.openonstart true`. Not sure if the documentation needs to be updated or not.

**Comment by tommyshem** [comment]
micro version 2 changed the options naming by putting a dot inbetween plugin name and option setting. We are curretly changing the plugin to work with micro version 2. Micro 2 currently uses a fork of this project with v2 support from here https://github.com/micro-editor/updated-plugins/tree/master/filemanager-plugin. This is what you get if you installed it with `plugin install filemanager`

I will make sure the docs get changed, thank you for reporting the solution.
