### ISSUE TITLE
working well for me.. But how to change folders

### ISSUE THREAD

**Issue by gedw99** [NicolaiSoeborg/filemanager-plugin#5]
i am on OSX.
I cant seem to be able to navigate folders or open a file from the tree.
Is this supported ?

**Comment by tommyshem** [comment]
You need Micro Editor version 1.3.2 and above for this to work.
I am on Linux and it works.
When you are in the tree window move to the file you want to open with the cursor keys and just press enter key to open the file highlighted.
To go up a folder use cursors to .. and press eneter. 
To select a folder move the cursor to the folder you need to open and press eneter key, to enter the folder.
I have not tested on OSX as I have no access to one.
If it does not work then please leave feed back and I will try and fix it.

**Comment by gedw99** [comment]
thanks

It works the way you said on OSX and linxux.

Why is this not part of the main micro plugns i wonder? It makes it hard to find yours btw.

**Comment by NicolaiSoeborg** [comment]
I don't know why it was removed from the official repo:
 * https://github.com/micro-editor/plugin-channel/commit/81999d3aace9a236b90aab70d58df5f7d29c89ef

I wasn't contacted about these 'bugs', but I will try to create a new PR to get it included again.

Btw I've added mouse support in the newest release (v2.1.0) so closing this issue :-)

**Comment by gedw99** [comment]
Mouse support ! Thank you.

Yes see if you can get included on the plugins list.
