### ISSUE TITLE
[bug] plugin doesn't work

### ISSUE THREAD

**Issue by inaciomdrs** [NicolaiSoeborg/filemanager-plugin#51]
I have installed this plugin with micro in Ubuntu 18.04, but it doesn't work, namely, file tree doesn't appear.

**Comment by sum01** [comment]
What version of micro are you on? The new v2 broke the plugin

**Comment by inaciomdrs** [comment]
Hm, this explains. I'm using v2.2, i believe that's the minor. The major is surely 2

**Comment by sum01** [comment]
Alright, then I'll close this just because it's essentially the same as https://github.com/NicolaiSoeborg/filemanager-plugin/issues/50

The (temporary) solution is also in that issue.
