### ISSUE TITLE
How to install? "bash: plugin: command not found" 

### ISSUE THREAD

**Issue by sirakai-pc** [NicolaiSoeborg/filemanager-plugin#54]
How do I install this plugin? 

**Errors:**
$ plugin install filemanager
bash: plugin: command not found

$ sudo pacman -S plugin
[sudo] password for sirakai: 
error: target not found: plugin

**Comment by sum01** [comment]
Micro plugins are installed by running that command from inside Micro, not your terminal.

But this plugin doesn't currently work with v2 of Micro anyways. Please see https://github.com/NicolaiSoeborg/filemanager-plugin/issues/50
