### ISSUE TITLE
Is there a way to open a file in a new micro tab from tree 

### ISSUE THREAD

**Issue by FilipeAdao96** [NicolaiSoeborg/filemanager-plugin#55]
Currently when i tab a file open on Tree view it opens in vsplit (divides my current pane ) is there a hotkey or a way to bind it so it opens it in a new tab  ?  i searched but could not find any way around this. 

Thanks in advance !

**Comment by sum01** [comment]
Not yet implemented.
See https://github.com/NicolaiSoeborg/filemanager-plugin/issues/26
